Make EPS & SVG Rendering usable on international locales
Bacon/BaconQrCode pull request #84
Opened 2021-05-24 15:21 UTC by bardiir

Funnily enough - This does not fix the Imagick rendering as even the base PHP function of ImagickDraw::scale(float, float) does fail on international locale with floats. But it does take care of localized numeric transformations giving broken SVGs when using the library, it's at least usable with the svg and eps backends without giving spontaneous errors.

I also opened an issue there: https://github.com/Imagick/imagick/issues/404

The error you're seeing when using Imagick Backend on an international locale is going to be 'non-conforming drawing primitive definition `'

I'm probably still going to use an en_US locale now and do numeric transformations manually instead of via PHP instead. But it's anyway a good idea to support other locales, so this is at least an improvement over the original.

2021-05-24 15:36 UTC, DASPRiD commented
Generally looks fine, though two things about this:

- `%F` is not omitting redundant trailing zeros 
- The lines seems to became pretty long - they should not exceed 120 character.
- Bonus: Spaces around the `.` operator :)

As `%F` does not omit trailing zeros, an alternative could be to have a helper function in the respective renderers which replaces the call to `round()` and instead use its own implementation which outputs non-locale aware numbers as strings.

Considering the last PR, it should actually be fine to combine `number_format()` with `round()` in its own function.

2021-06-17 15:10 UTC, Francismori7 commented
Please merge this. On a French production server, scale gets rendered as 2,572 instead of 2.572 which in turn causes a very big scaling problem.

We're currently resorting to a STR_REPLACE around the generate function and is not really ideal.

2021-06-17 15:12 UTC, DASPRiD requested changes
See previous comment.

2021-12-10 15:21 UTC, SerkanBe commented
Ran into the same issue, setting the locale settings now around the QR-generation. Not ideal, but does the job. Without any str_replace or changes to the classes.

```
$locale = setlocale(LC_ALL, 0);
setlocale(LC_ALL, 'C');
try {
    $renderer = new ImageRenderer(
        new RendererStyle(132, 2),
        new SvgImageBackEnd()
    );

    $writer = new Writer($renderer);
    return $writer->writeString($data);
} finally {
    setlocale(LC_ALL, $locale);
}
```


Would it make sense to have this done in writeString()? I might be missing something... but it seems to work for me just fine.

2024-03-18 01:27 UTC, DASPRiD commented
This has been addressed by #100.

2024-03-18 01:27 UTC, closed without merging